---
- name: Setup Remote Host
  hosts: "{{ host_ip }}"
  become: yes
  vars:
    username: "{{ username }}"
    password: "{{ password }}"
    ssh_key: "{{ ssh_key }}"
    packages: "{{ packages.split(',') }}"
    config_files: "{{ config_files.split(',') }}"

  tasks:
    - name: Ensure user exists
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present

    - name: Add SSH key to user's authorized_keys
      authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_key }}"
        state: present

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: Deploy configuration files
      copy:
        src: "{{ item }}"
        dest: "/etc/{{ item | basename }}"
      loop: "{{ config_files }}"
